### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by Joab0** [squarecloudofc/docs#7]
Path: all endpoints that send files

Requests made to these endpoints receive timeout (504) because the files are not sent
![image](https://github.com/user-attachments/assets/808f463f-eb26-4cc9-b5a2-7ec7b74688bc)

**Comment by JoaoOtavioS** [comment]
Thanks for report this issue. @Sinvaldo-Neto, can you check with the Mintlify team? Anyway, I'll see if I can report it too.

**Comment by ghost** [comment]
Thank you for the report. I have already checked with the Mintlify team, and they informed me that they are working on resolving the issue.
